trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    mvn clean test
  displayName: 'Execute Autoc0de - Playwright tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'target/ExtentReport-HTML.html'
    testRunTitle: 'Test Report'
  displayName: 'Publish Reports'

- task: PublishCucumberReport@1
  inputs:
    jsonDir: './target/Reports'
    outputPath: './target'
    theme: 'bootstrap'
    reportSuiteAsScenarios: true
    name: 'Autoc0dePlaywrigth'
    title: 'Autoc0de Playwright'