name: Autoc0de-Playwright

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '19.0.2'
        distribution: 'adopt'
    - name: Execute Tests
      run: mvn clean install
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2.2.2
      with:
        name: Cucumber Reports
        path: target/Reports
